### ISSUE TITLE
The plugin was not activated

### ISSUE THREAD

**Issue by mastakby** [ElementsProject/woocommerce-gateway-lightning#6] opened 2018-01-17 11:52 UTC
Woocommerce 

The plugin was not activated, because it caused a fatal error.
Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /home/user2040175/www/d0015477.atservers.net/wp-content/plugins/woocommerce-gateway-lightning/woocommerce-gateway-lightning.php on line 224

**Comment by dlerario** [comment] 2018-01-17 17:16
I got the same error here

**Comment by weex** [comment] 2018-01-17 23:20
Does it require a specific php version?

**Comment by shesek** [comment] 2018-01-18 11:05
The plugin has been running on PHP 7.0.22 and hasn't yet been tested with other versions.

It looks like the error you're getting was due to a bug that [was fixed yesterday](https://github.com/ElementsProject/woocommerce-gateway-lightning/commit/39953439301a83b9852f9a965a3d57ffb31ac6c6), but which was only causing a deprecation notice without breaking anything for 7.0.22 (`Non-static method WooCommerce::api_request_url() should not be called statically`). It appears like other PHP versions (newer ones, probably?) treat this as a fatal error instead.

I just tagged and released and [v0.1.4](https://github.com/ElementsProject/woocommerce-gateway-lightning/releases/tag/v0.1.4) with that fix, should be resolved now.

Note, however, that the plugin is using some of PHP 7 features and currently not compatible with PHP 5. I was planning to eventually modify this to work with PHP 5, will keep track of that at #7.

**Comment by shesek** [comment] 2018-01-18 13:00
Actually, it appears like these features were introduced in PHP 5.6, not PHP 7. I just tested with PHP 5.6, everything seems to work fine!

**Comment by shesek** [comment] 2018-01-21 00:31
@mastakby @dlerario @weex so, is it working now? :)

**Comment by weex** [comment] 2018-01-21 01:16
@shesek still haven't gotten an email confirmation. Haven't tried to order anything else. Let me know if you need more info.

**Comment by shesek** [comment] 2018-01-21 01:30
@weex I understand that emails are going to be sent out in the next day or two (no one got them yet, due to a server misconfiguration). But I've inspected your order manually and confirmed with the folks responsible for this at Blockstream that your order is marked as paid and queued for delivery.

**Closed as completed** 2018-01-21 16:53 UTC
